// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXz_6UF9Yv2us27hWAYfBKhS2M0AOmPo4',
    appId: '1:693200674577:web:45a4b2dc200214d138f6b0',
    messagingSenderId: '693200674577',
    projectId: 'applink-demo-project',
    authDomain: 'applink-demo-project.firebaseapp.com',
    storageBucket: 'applink-demo-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56w1ZXkWyYWaNDCgk0c7sS1JXjEIw92I',
    appId: '1:693200674577:android:6910ade8a92839b838f6b0',
    messagingSenderId: '693200674577',
    projectId: 'applink-demo-project',
    storageBucket: 'applink-demo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhUxghP-0SrHYdCff6q2kW8kpki_4Dxg',
    appId: '1:693200674577:ios:03dc0e2c17bdef4438f6b0',
    messagingSenderId: '693200674577',
    projectId: 'applink-demo-project',
    storageBucket: 'applink-demo-project.appspot.com',
    iosBundleId: 'com.example.applinkDemoAdminPanel',
  );
}
